
<?php
/**
 * file: dossier_theme.module
 *
 * Themes of a dossier block. 
 *
 * Paul Mulholland <p.mulholland@open.ac.uk>
 *
 */

/**
* Implements hook_block_info().
*/
function dossier_theme_block_info() {
  $blocks = array();
  $blocks['dossier_theme_block'] = array(
    'info' => t('Themes of a dossier'),
  );
  return $blocks;
}
/**
* Implements hook_block_view().
*/
function dossier_theme_block_view($delta = '') {
  $block = array();
  switch ($delta) {
    case 'dossier_theme_block':
      $block['subject'] = '';
      $block['content'] = dossier_theme_block_content();
      break;
  }
  return $block;
}

function dossier_theme_block_content() {
	$path = request_path();
	$path_array = explode('/',request_path());
	if(isset($path_array[0]) && isset($path_array[1]) && !isset($path_array[2])) {
		$dossier_nid = (int) $path_array[1];
		if($path_array[0] == 'dossier' && $dossier_nid) {
			return dec_dossier_themes($dossier_nid);
		}
	}
  return FALSE;
}

function dec_dossier_themes($dossier_nid) {
	$dossier_node = node_load($dossier_nid);
	$story_array = read_stories_from_dossier_node($dossier_node);
	$themes = themes_for_a_dossier($story_array, 10);
	$output = '';
	$output = '<div>&nbsp';
	if(!empty($themes)) {
		$output .= '<div class="topic-block"><h2 class="pane-title"><i class="fa fa-link fa-lg">&nbsp;</i><span class="topic-title">Dossier themes&nbsp;&nbsp;</span>' . '</h2></div>';
		$output .=  '<ul class="field-name-field-fb-tags">';
		foreach($themes as $theme) {
			$output .= l('<li class="tags">'.$theme->name."</li>", request_path(), array("html"=>TRUE, 'query'=>array('tag'=>$theme->value)));
		}
		$output .=  '</ul><div style="clear:both;"></div>';
	}
	$settings = settings_for_a_dossier($story_array, 10);
	if(!empty($settings)) {
		$output .= '<div class="topic-block"><h2 class="pane-title"><i class="fa fa-compass fa-lg">&nbsp;</i><span class="topic-title">Dossier settings&nbsp;&nbsp;</span>' . '</h2></div>';
		$output .=  '<ul class="field-name-field-fb-tags">';
		foreach($settings as $setting) {
			if($setting->end && $setting->start && $setting->start !== $setting->end) {
				$output .= l('<li class="tags">'. $setting->name.", ".$setting->start." to ".$setting->end . '</li>',request_path(), array('html'=>'true', 'query' => array('location' => $setting->location, 'time' => $setting->start, 'end' => $setting->end)));				
			}
			elseif($setting->start == $setting->end) {
				$output .= l('<li class="tags">'. $setting->name.", ".$setting->start . '</li>',request_path(), array('html'=>'true', 'query' => array('location' => $setting->location, 'time' => $setting->start)));
			}
			elseif($setting->start && !$setting->end) {
				$output .= l('<li class="tags">'. $setting->name.", ".$setting->start . '</li>',request_path(), array('html'=>'true', 'query' => array('location' => $setting->location, 'time' => $setting->start)));
			}
			elseif($setting->end && !$setting->start) {
				$output .= l('<li class="tags">'. $setting->name.", ".$setting->end . '</li>',request_path(), array('html'=>'true', 'query' => array('location' => $setting->location, 'time' => $setting->end)));
			}
		
		}
	$output .=  '</ul><div style="clear:both;"></div>';
	}
	return $output.'</div>';
}


/**
 * Get settings for a story
 */
function settings_for_a_dossier($story_array, $n = 10) {
	$output = array();
	if(!empty($story_array)) {
		$story_string = "('".implode("','", $story_array)."')";	
		$query = "SELECT *
FROM
(SELECT COUNT(DISTINCT event_location_start.id) as stories, COUNT(DISTINCT event_location_start.tag) as tags, COUNT(DISTINCT event_location_start.event) as frequency, event_location_start.location, event_location_start.start, event_end.end
FROM
(
SELECT events_table.id, events_table.tag, events_table.event, events_table.location, event_start_table.start
FROM
(SELECT DISTINCT query_tag.id, query_tag.tag, event_attribute_value.event, location_table.value as location
FROM tag_event_id, query_tag, event_attribute_value, event_attribute_value as location_table, event_attribute_value as start_table, attribute_name as location_attribute_name, attribute_name as time_attribute_name
WHERE query_tag.id IN ".$story_string." AND
query_tag.tag = tag_event_id.tag AND
tag_event_id.event_id = event_attribute_value.event AND
event_attribute_value.event = location_table.event AND
event_attribute_value.event = start_table.event AND
location_table.attribute = location_attribute_name.attribute AND
location_attribute_name.name = 'location' AND
((start_table.attribute = time_attribute_name.attribute AND
time_attribute_name.name = 'start_time') OR
(start_table.attribute = time_attribute_name.attribute AND
time_attribute_name.name = 'end_time'))) as events_table
LEFT JOIN
(SELECT DISTINCT query_tag.tag, event_attribute_value.event, location_table.value as location, start_table.value as start
FROM tag_event_id, query_tag, event_attribute_value, event_attribute_value as location_table, event_attribute_value as start_table, attribute_name as location_attribute_name, attribute_name as time_attribute_name
WHERE query_tag.id IN ".$story_string." AND
query_tag.tag = tag_event_id.tag AND
tag_event_id.event_id = event_attribute_value.event AND
event_attribute_value.event = location_table.event AND
event_attribute_value.event = start_table.event AND
location_table.attribute = location_attribute_name.attribute AND
location_attribute_name.name = 'location' AND
start_table.attribute = time_attribute_name.attribute AND
time_attribute_name.name = 'start_time') as event_start_table ON event_start_table.event = events_table.event
) as event_location_start
LEFT JOIN
(SELECT event_attribute_value.event, end_table.value as end
FROM tag_event_id, query_tag, event_attribute_value, event_attribute_value as end_table, attribute_name as time_attribute_name
WHERE query_tag.id IN ".$story_string." AND
query_tag.tag = tag_event_id.tag AND
tag_event_id.event_id = event_attribute_value.event AND
event_attribute_value.event = end_table.event AND
end_table.attribute = time_attribute_name.attribute AND
time_attribute_name.name = 'end_time') as event_end ON event_location_start.event = event_end.event
GROUP BY event_location_start.location, event_location_start.start, event_end.end) as frequency_table
JOIN tag_name ON tag_name.tag = frequency_table.location ORDER BY stories DESC, tags DESC, frequency DESC LIMIT ".$n.";";
		$output = array();
		$result = db_query($query);
		$output = array();
		foreach ($result as $record) {
			$output[] = $record;
		}
	}
	return $output;
}

/**
 * Calculate themes for a dossier
 * Find how many times a concept appears in the concept spaces of the annotations of the stoires in the dossier
 * Group by number of stories they connect to, number of annotations they connect to, and finally frequency
 */
function themes_for_a_dossier($story_array, $limit = 10) {//****here
	$output = array();
	if(!empty($story_array)) {
		$story_string = "('".implode("','", $story_array)."')";
		$query = "SELECT *
FROM
(SELECT tag_name.tag as value, tag_name.name, COUNT(tag_name.tag) as frequency, COUNT(DISTINCT data.annotation) annotations, COUNT(DISTINCT data.id) as stories 
FROM tag_name,
(SELECT tag_name.tag, query_tag.tag as annotation, query_tag.id
FROM tag_attribute, tag_attribute_id_value, tag_name, query_tag, theme_fact_property
WHERE 
query_tag.id IN ".$story_string." AND
query_tag.tag = tag_attribute.tag AND
tag_attribute.attribute = theme_fact_property.fb_property AND
tag_attribute.id = tag_attribute_id_value.tag_attribute_id and
tag_name.tag = tag_attribute_id_value.value
UNION ALL
SELECT tag_name.tag, query_tag.tag as annotation, query_tag.id
FROM tag_attribute, tag_attribute_id_value, tag_name, query_tag, theme_fact_property, fact_attribute_reverse
WHERE 
query_tag.id IN ".$story_string." AND
query_tag.tag = tag_attribute_id_value.value AND
tag_attribute_id_value.tag_attribute_id = tag_attribute.id AND 
tag_attribute.attribute = fact_attribute_reverse.attribute AND
fact_attribute_reverse.reverse = theme_fact_property.fb_property AND
tag_name.tag = tag_attribute.tag
UNION ALL
SELECT event_attribute_value.value as tag, event_table.tag as annotation, event_table.id
FROM 
(SELECT DISTINCT query_tag.tag, event_attribute_value.event, query_tag.id
FROM query_tag, event_attribute_value
WHERE 
query_tag.id IN ".$story_string." AND
query_tag.tag = event_attribute_value.value) as event_table, event_attribute_value, attribute_name
WHERE event_table.event = event_attribute_value.event AND
event_attribute_value.attribute = attribute_name.attribute AND
attribute_name.name <> 'location') as data
WHERE tag_name.tag = data.tag
GROUP BY tag_name.tag
ORDER BY stories DESC, annotations DESC, frequency DESC) as result
WHERE result.frequency >= 2 LIMIT ".$limit.";";
		$result = db_query($query);
		foreach ($result as $record) {
			$output[] = $record;
		}
	}
	return $output;
}

function read_stories_from_dossier_node($dossier_node) {
	$output = array();
	$field_stories = $dossier_node->field_stories;
	if(isset($field_stories['und'][0])) {
		foreach($field_stories['und'] as $story_value) {
			if(isset($story_value['target_id'])) {
				$output[] = $story_value['target_id'];
			}
		}
	}
	return $output;
}


