
<?php
/**
 * file: dossier_theme.module
 *
 * Themes of a dossier block. 
 *
 * Paul Mulholland <p.mulholland@open.ac.uk>
 *
 */

/**
* Implements hook_block_info().
*/
function dossier_theme_block_info() {
  $blocks = array();
  $blocks['dossier_theme_block'] = array(
    'info' => t('Themes of a dossier'),
  );
  return $blocks;
}
/**
* Implements hook_block_view().
*/
function dossier_theme_block_view($delta = '') {
  $block = array();
  switch ($delta) {
    case 'dossier_theme_block':
      $block['subject'] = '';
      $block['content'] = dossier_theme_block_content();
      break;
  }
  return $block;
}

function dossier_theme_block_content() {
	$path = request_path();
	$path_array = explode('/',request_path());
	if(isset($path_array[0]) && isset($path_array[1]) && !isset($path_array[2])) {
		$dossier_nid = (int) $path_array[1];
		if($path_array[0] == 'dossier' && $dossier_nid) {
			return dec_dossier_themes($dossier_nid);
		}
	}
  return FALSE;
}

function dec_dossier_themes($dossier_nid) {
	$dossier_node = node_load($dossier_nid);
	$themes = themes_for_a_dossier($dossier_node, 10);
	$output = '';
	if(!empty($themes)) {
		$output .= '<div style="clear:both"><h2><i class="fa fa-link fa-lg">&nbsp;</i>Dossier themes</h2></div>';
		$output .=  '<div><ul class="field-name-field-fb-tags">';
		foreach($themes as $theme) {
			$output .= storytaglink('<li class="tags">'.$theme->name."</li>", $theme->value, array("html"=>TRUE));
		}
		$output .=  '</ul></div>';
	}
	return $output;
}

/**
 * Calculate themes for a dossier
 */
function themes_for_a_dossier($dossier_node, $limit = 10) {//****here
	$output = array();
	$story_array = read_stories_from_dossier_node($dossier_node);
	if(!empty($story_array)) {
		$story_string = "('".implode("','", $story_array)."')";
		$query = "SELECT story_tag_event_value.value, story_tag_event_value.stories, story_tag_event_value.tags, story_tag_event_value.events, tag_name.name
FROM
(SELECT  COUNT(DISTINCT query_tag.id) as stories, COUNT(DISTINCT query_tag.tag) as tags, COUNT(DISTINCT value_table.event) as events, value_table.value
FROM query_tag, tag_event_id, event_attribute_value as value_table
WHERE query_tag.id IN ".$story_string." AND
query_tag.tag = tag_event_id.tag AND
value_table.event = tag_event_id.event_id AND
value_table.attribute <> 'location'
GROUP BY value_table.value
ORDER BY stories DESC, tags DESC, events DESC) as story_tag_event_value, tag_name
WHERE story_tag_event_value.value = tag_name.tag LIMIT ".$limit.";";
		$result = db_query($query);
		foreach ($result as $record) {
			$output[] = $record;
		}
	}
	return $output;
}

function read_stories_from_dossier_node($dossier_node) {
	$output = array();
	$field_stories = $dossier_node->field_stories;
	if(isset($field_stories['und'][0])) {
		foreach($field_stories['und'] as $story_value) {
			if(isset($story_value['target_id'])) {
				$output[] = $story_value['target_id'];
			}
		}
	}
	return $output;
}

