
<?php
/**
 * file: story_search_theme.module
 *
 * Themes of a story search. 
 *
 * Paul Mulholland <p.mulholland@open.ac.uk>
 *
 */

/**
* Implements hook_block_info().
*/
function story_search_theme_block_info() {
  $blocks = array();
  $blocks['story_search_theme_block'] = array(
    'info' => t('Themes of a story search'),
  );
  return $blocks;
}
/**
* Implements hook_block_view().
*/
function story_search_theme_block_view($delta = '') {
  $block = array();
  switch ($delta) {
    case 'story_search_theme_block':
      $block['subject'] = '';
      $block['content'] = story_search_theme_block_content();
      break;
  }
  return $block;
}

function story_search_theme_block_content() {
	$n = 8;
	$path = request_path();
	$path_array = explode('/',request_path());
	$rpa = array_reverse($path_array);
	
	$story_tag = FALSE;
	if(isset($rpa[2]) && $rpa[2] == 'stories') {
		$story_tag = '/'.$rpa[1].'/'.$rpa[0];
		$option = FALSE;
	}
	elseif(isset($rpa[3]) && $rpa[3] == 'stories') {
		$story_tag = '/'.$rpa[2].'/'.$rpa[1];
		$option = $rpa[0];
	}
	if($story_tag) {
		$name = get_topic_name($story_tag);
		if(!$name) {
			$name = $story_tag;
		}
		
		if($option == 'themes') {
			//stories ordered according to their theme match
			$query = "SELECT  query_tag.id, COUNT(DISTINCT query_tag.tag) as tags, COUNT(DISTINCT value_table.event) as events
	FROM query_tag, tag_event_id, event_attribute_value as value_table
	WHERE
	value_table.value = '".$story_tag."' AND
	value_table.event = tag_event_id.event_id AND
	query_tag.tag = tag_event_id.tag AND
	value_table.attribute <> 'location'
	GROUP BY query_tag.id
	ORDER BY tags DESC, events DESC LIMIT ".$n.";";
		}
		else {
			$query = "SELECT result_list.id, order_list.tags, order_list.events
FROM
(SELECT query_tag.id
FROM query_tag
WHERE query_tag.tag = '".$story_tag."') as result_list
LEFT JOIN
(SELECT  query_tag.id, COUNT(DISTINCT query_tag.tag) as tags, COUNT(DISTINCT value_table.event) as events
FROM query_tag, tag_event_id, event_attribute_value as value_table
WHERE
value_table.value = '".$story_tag."' AND
value_table.event = tag_event_id.event_id AND
query_tag.tag = tag_event_id.tag AND
value_table.attribute <> 'location'
GROUP BY query_tag.id
ORDER BY tags DESC, events DESC LIMIT ".$n.") as order_list
ON
result_list.id = order_list.id;";
		}
		$result = db_query($query);
		$story_array = array();
		foreach ($result as $record) {
			$story_array[] = $record->id;
		}
		
		//themes for the set of stories
		$themes = themes_for_a_dossier($story_array);
		$output = '';
		$output = '<div>&nbsp';
		if(!empty($themes)) {
			$output .= '<div class="topic-block"><h2 class="pane-title"><i class="fa fa-link fa-lg">&nbsp;</i><span class="topic-title">Themes of stories&nbsp;&nbsp;</span>' . '</h2></div>';
			$output .=  '<div><ul class="field-name-field-fb-tags">';
			foreach($themes as $theme) {
				$output .= l('<li class="tags">'.$theme->name."</li>", request_path(), array("html"=>TRUE, "query"=>array("tag"=>$theme->value, "storytag"=>$story_tag)));
			}
			$output .=  '</ul><div style="clear:both;"></div>';
			$output .=  '</div>';
		}
		
		//settings for the set of stories
		$settings = settings_for_a_dossier($story_array);

		if(!empty($settings)) {
			$output .= '<div class="topic-block"><h2 class="pane-title"><i class="fa fa-compass fa-lg">&nbsp;</i><span class="topic-title">Settings of stories&nbsp;&nbsp;</span>' . '</h2></div>';
			$output .=  '<ul class="field-name-field-fb-tags">';
			foreach($settings as $setting) {
				
				if($setting->end && $setting->start && $setting->start !== $setting->end) {
					$output .= l('<li class="tags">'. $setting->name.", ".$setting->start." to ".$setting->end . '</li>',request_path(),array('html'=>'true', 'query' => array('location' => $setting->location, 'time' => $setting->start, 'end' => $setting->end)));
				}
				elseif($setting->end && $setting->start && $setting->start == $setting->end) {
					$output .= l('<li class="tags">'. $setting->name.", ".$setting->start . '</li>',request_path(), array('html'=>'true', 'query' => array('location' => $setting->location, 'time' => $setting->start)));
				}
				elseif($setting->time) {
					$output .= l('<li class="tags">'. $setting->name.", ".$setting->time . '</li>',request_path(),array('html'=>'true', 'query' => array('location' => $setting->location, 'time' => $setting->time)));
				}
				
// 				if($setting->end && $setting->start && $setting->start !== $setting->end) {
// 					$output .= l('<li class="tags">'. $setting->name.", ".$setting->start." to ".$setting->end . '</li>',request_path() ,array('html'=>'true', 'query' => array("storytag"=>$story_tag, 'location' => $setting->location, 'time' => $setting->start, 'end' => $setting->end)));
// 				}
// 				elseif($setting->start == $setting->end) {
// 					$output .= l('<li class="tags">'. $setting->name.", ".$setting->start . '</li>',request_path() , array('html'=>'true', 'query' => array("storytag"=>$story_tag, 'location' => $setting->location, 'time' => $setting->start)));
// 				}
// 				elseif($setting->start && !$setting->end) {
// 					$output .= l('<li class="tags">'. $setting->name.", ".$setting->start . '</li>',request_path() ,array('html'=>'true', 'query' => array("storytag"=>$story_tag, 'location' => $setting->location, 'time' => $setting->start)));
// 				}
// 				elseif($setting->end && !$setting->start) {
// 					$output .= l('<li class="tags">'. $setting->name.", ".$setting->end . '</li>',request_path() ,array('html'=>'true', 'query' => array("storytag"=>$story_tag, 'location' => $setting->location, 'time' => $setting->end)));
// 				}
		
			}
			$output .=  '</ul><div style="clear:both;"></div>';
		}
		
		return $output.'</div>';
	}
	elseif(isset($_GET['storylocation'])) {
		$location = $_GET['storylocation'];
		$start = $_GET['storytime'];
		if(isset($params['storyend'])) {
			$end = $params['storyend'];
		}
		else {
			$end = 0;
		}
		
		if($start && $end) {
			//query
			$query = "SELECT result_table.id, COUNT(result_table.tag) as tags
FROM
(SELECT DISTINCT event_location_start.id, event_location_start.tag, event_location_start.event, event_location_start.location, event_location_start.start, event_end.end
FROM
(
SELECT events_table.id, events_table.tag, events_table.event, events_table.location, event_start_table.start
FROM
(SELECT DISTINCT query_tag.id, query_tag.tag, event_attribute_value.event, location_table.value as location
FROM tag_event_id, query_tag, event_attribute_value, event_attribute_value as location_table, event_attribute_value as start_table, attribute_name as location_attribute_name, attribute_name as time_attribute_name
WHERE
query_tag.tag = tag_event_id.tag AND
tag_event_id.event_id = event_attribute_value.event AND
event_attribute_value.event = location_table.event AND
event_attribute_value.event = start_table.event AND
location_table.value = '".$location."' AND
location_table.attribute = location_attribute_name.attribute AND
location_attribute_name.name = 'location' AND
((start_table.attribute = time_attribute_name.attribute AND
time_attribute_name.name = 'start_time') OR
(start_table.attribute = time_attribute_name.attribute AND
time_attribute_name.name = 'end_time'))) as events_table
LEFT JOIN
(SELECT DISTINCT query_tag.tag, event_attribute_value.event, location_table.value as location, start_table.value as start
FROM tag_event_id, query_tag, event_attribute_value, event_attribute_value as location_table, event_attribute_value as start_table, attribute_name as location_attribute_name, attribute_name as time_attribute_name
WHERE
query_tag.tag = tag_event_id.tag AND
tag_event_id.event_id = event_attribute_value.event AND
event_attribute_value.event = location_table.event AND
event_attribute_value.event = start_table.event AND
location_table.attribute = location_attribute_name.attribute AND
location_attribute_name.name = 'location' AND
start_table.attribute = time_attribute_name.attribute AND
time_attribute_name.name = 'start_time') as event_start_table ON event_start_table.event = events_table.event
) as event_location_start
LEFT JOIN
(SELECT DISTINCT event_attribute_value.event, end_table.value as end
FROM tag_event_id, query_tag, event_attribute_value, event_attribute_value as end_table, attribute_name as time_attribute_name
WHERE
query_tag.tag = tag_event_id.tag AND
tag_event_id.event_id = event_attribute_value.event AND
event_attribute_value.event = end_table.event AND
end_table.attribute = time_attribute_name.attribute AND
time_attribute_name.name = 'end_time') as event_end ON event_location_start.event = event_end.event) as result_table
WHERE (result_table.start < '".$end."' AND result_table.end > '".$start."') OR (result_table.start > '".$start."' AND result_table.start < '".$end."') OR (result_table.end > '".$start."' AND result_table.end < '".$end."')
GROUP BY result_table.id
ORDER BY tags;";
		}
		if($start || $end) {
			if($start) {
				$time = $start;
			}
			else {
				$time = $end;
			}
			//query
			$query = "SELECT result_table.id, COUNT(result_table.tag) as tags
FROM
(SELECT DISTINCT event_location_start.id, event_location_start.tag, event_location_start.event, event_location_start.location, event_location_start.start, event_end.end
FROM
(
SELECT events_table.id, events_table.tag, events_table.event, events_table.location, event_start_table.start
FROM
(SELECT DISTINCT query_tag.id, query_tag.tag, event_attribute_value.event, location_table.value as location
FROM tag_event_id, query_tag, event_attribute_value, event_attribute_value as location_table, event_attribute_value as start_table, attribute_name as location_attribute_name, attribute_name as time_attribute_name
WHERE
query_tag.tag = tag_event_id.tag AND
tag_event_id.event_id = event_attribute_value.event AND
event_attribute_value.event = location_table.event AND
event_attribute_value.event = start_table.event AND
location_table.value = '".$location."' AND
location_table.attribute = location_attribute_name.attribute AND
location_attribute_name.name = 'location' AND
((start_table.attribute = time_attribute_name.attribute AND
time_attribute_name.name = 'start_time') OR
(start_table.attribute = time_attribute_name.attribute AND
time_attribute_name.name = 'end_time'))) as events_table
LEFT JOIN
(SELECT DISTINCT query_tag.tag, event_attribute_value.event, location_table.value as location, start_table.value as start
FROM tag_event_id, query_tag, event_attribute_value, event_attribute_value as location_table, event_attribute_value as start_table, attribute_name as location_attribute_name, attribute_name as time_attribute_name
WHERE
query_tag.tag = tag_event_id.tag AND
tag_event_id.event_id = event_attribute_value.event AND
event_attribute_value.event = location_table.event AND
event_attribute_value.event = start_table.event AND
location_table.attribute = location_attribute_name.attribute AND
location_attribute_name.name = 'location' AND
start_table.attribute = time_attribute_name.attribute AND
time_attribute_name.name = 'start_time') as event_start_table ON event_start_table.event = events_table.event
) as event_location_start
LEFT JOIN
(SELECT DISTINCT event_attribute_value.event, end_table.value as end
FROM tag_event_id, query_tag, event_attribute_value, event_attribute_value as end_table, attribute_name as time_attribute_name
WHERE
query_tag.tag = tag_event_id.tag AND
tag_event_id.event_id = event_attribute_value.event AND
event_attribute_value.event = end_table.event AND
end_table.attribute = time_attribute_name.attribute AND
time_attribute_name.name = 'end_time') as event_end ON event_location_start.event = event_end.event) as result_table
WHERE result_table.start = '".$time."' OR result_table.end = '".$time."' OR (result_table.start < '".$time."' AND result_table.end > '".$time."')
GROUP BY result_table.id
ORDER BY tags;";
		
		}
		$result = db_query($query);
		$story_array = array();
		foreach ($result as $record) {
			$story_array[] = $record->id;
		}
		//themes for the set of stories
		$themes = themes_for_a_dossier($story_array);
		$output = '';
		$output = '<div>&nbsp';
		if(!empty($themes)) {
			$output .= '<div class="topic-block"><h2 class="pane-title"><i class="fa fa-link fa-lg">&nbsp;</i><span class="topic-title">Themes of stories&nbsp;&nbsp;</span>' . '</h2></div>';
			$output .=  '<div><ul class="field-name-field-fb-tags">';
			foreach($themes as $theme) {
				$output .= l('<li class="tags">'.$theme->name."</li>", request_path(), array("html"=>TRUE, "query"=>array("tag"=>$theme->value, 'storylocation'=>$location, 'storytime'=>$start, 'storyend'=>$end)));
			}
			$output .=  '</ul><div style="clear:both;"></div>';
			$output .=  '</div>';
		}
		$output .= '</div>';
		
		return $output;
	}
	return;
}


